name: Run K6

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "branch name (Default: main)"
        required: true
        default: "main"
        
env:
  NR_ACCOUNT_ID: ${{ secrets.NR_ACCOUNT_ID }}
  NR_API_KEY: ${{ secrets.NR_API_KEY }}
  
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Run container
        run: |
          docker run \
          -d --restart unless-stopped \
          --name newrelic-statsd \
          -h $(hostname) \
          -e NR_ACCOUNT_ID="${NR_ACCOUNT_ID}" \
          -e NR_API_KEY="${NR_API_KEY}" \
          -p 8125:8125/udp \
          newrelic/nri-statsd:latest
          
      - name: sleep 
        run: sleep 60
        
      - name: Create script
        run: echo "import http from 'k6/http'; import { sleep } from 'k6'; export default function() { http.get('http://emea-partners.newrelic-es.com'); sleep(1); }" > script.js
  
  
      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build xk6-counter binary
        run: xk6 build --with github.com/mstoykov/xk6-counter@latest
        
      - name: run tests
        run : ./k6 run --vus 12 --duration 30s --out statsd script.js

